// Lista de poblaciones de Catalunya (las 4 provincias), pensada para el
// selector de "Ciudad" en Empresas. No pretende ser el listado oficial
// completo de los ~950 municipios — es una selección amplia de capitales
// de comarca y poblaciones grandes/medianas, ordenada alfabéticamente y
// sin duplicados. El selector siempre permite escribir a mano cualquier
// población que no esté aquí.
export const CIUDADES_CATALUNYA: string[] = [
  "Abrera",
  "Agramunt",
  "Aiguafreda",
  "Alcanar",
  "Alcarràs",
  "Alcover",
  "Alella",
  "Alp",
  "Amposta",
  "Arbúcies",
  "Arenys de Mar",
  "Arenys de Munt",
  "Argentona",
  "Artesa de Segre",
  "Badalona",
  "Bagà",
  "Balaguer",
  "Banyoles",
  "Barberà del Vallès",
  "Barcelona",
  "Begues",
  "Bellpuig",
  "Bellver de Cerdanya",
  "Berga",
  "Besalú",
  "Bigues i Riells",
  "Blanes",
  "Bordils",
  "Borges Blanques, Les",
  "Cabrera de Mar",
  "Cabrils",
  "Calaf",
  "Calafell",
  "Caldes d'Estrac",
  "Caldes de Malavella",
  "Caldes de Montbui",
  "Calella",
  "Calldetenes",
  "Cambrils",
  "Campdevànol",
  "Canet de Mar",
  "Canovelles",
  "Cardedeu",
  "Cardona",
  "Castellar del Vallès",
  "Castellbisbal",
  "Castelldefels",
  "Castelló d'Empúries",
  "Cerdanyola del Vallès",
  "Cervera",
  "Cornellà de Llobregat",
  "Cubelles",
  "Cunit",
  "Deltebre",
  "Els Hostalets de Pierola",
  "Esparreguera",
  "Esplugues de Llobregat",
  "Falset",
  "Figueres",
  "Flix",
  "Gandesa",
  "Garriga, La",
  "Gavà",
  "Gelida",
  "Girona",
  "Granollers",
  "Gualba",
  "Guissona",
  "Igualada",
  "Jonquera, La",
  "L'Ametlla de Mar",
  "L'Escala",
  "L'Hospitalet de Llobregat",
  "La Bisbal d'Empordà",
  "La Bisbal del Penedès",
  "La Pobla de Segur",
  "La Seu d'Urgell",
  "Les Franqueses del Vallès",
  "Llagostera",
  "Llançà",
  "Llavaneres, Sant Andreu de",
  "Lleida",
  "Lloret de Mar",
  "Malgrat de Mar",
  "Manlleu",
  "Manresa",
  "Martorell",
  "Masnou, El",
  "Masquefa",
  "Mataró",
  "Molins de Rei",
  "Mollerussa",
  "Mollet del Vallès",
  "Mont-roig del Camp",
  "Montblanc",
  "Montcada i Reixac",
  "Montgat",
  "Móra d'Ebre",
  "Móra la Nova",
  "Navàs",
  "Òdena",
  "Olesa de Montserrat",
  "Olot",
  "Palafrugell",
  "Palamós",
  "Palau-solità i Plegamans",
  "Pallejà",
  "Piera",
  "Pineda de Mar",
  "Pineda, La",
  "Pobla de Claramunt, La",
  "Polinyà",
  "Pont de Suert, El",
  "Prat de Llobregat, El",
  "Premià de Dalt",
  "Premià de Mar",
  "Puig-reig",
  "Puigcerdà",
  "Reus",
  "Ribes de Freser",
  "Ripoll",
  "Ripollet",
  "Riudoms",
  "Roda de Ter",
  "Roquetes",
  "Rubí",
  "Sabadell",
  "Sallent",
  "Salou",
  "Salt",
  "Sant Adrià de Besòs",
  "Sant Andreu de la Barca",
  "Sant Boi de Llobregat",
  "Sant Carles de la Ràpita",
  "Sant Celoni",
  "Sant Cugat del Vallès",
  "Sant Esteve Sesrovires",
  "Sant Feliu de Guíxols",
  "Sant Feliu de Llobregat",
  "Sant Fruitós de Bages",
  "Sant Hilari Sacalm",
  "Sant Joan de Vilatorrada",
  "Sant Joan Despí",
  "Sant Joan les Fonts",
  "Sant Julià de Vilatorta",
  "Sant Just Desvern",
  "Sant Pere de Ribes",
  "Sant Pol de Mar",
  "Sant Quirze del Vallès",
  "Sant Sadurní d'Anoia",
  "Sant Vicenç de Castellet",
  "Sant Vicenç dels Horts",
  "Santa Coloma de Farners",
  "Santa Coloma de Gramenet",
  "Santa Margarida de Montbui",
  "Santa Perpètua de Mogoda",
  "Santa Susanna",
  "Santpedor",
  "Sarrià de Ter",
  "Seva",
  "Sitges",
  "Solsona",
  "Sort",
  "Súria",
  "Tarragona",
  "Tàrrega",
  "Terrassa",
  "Tiana",
  "Tona",
  "Torelló",
  "Torredembarra",
  "Tortosa",
  "Tremp",
  "Ulldecona",
  "Vallirana",
  "Valls",
  "Vendrell, El",
  "Vic",
  "Vielha e Mijaran",
  "Vilablareix",
  "Viladecans",
  "Vilafranca del Penedès",
  "Vilanova del Camí",
  "Vilanova i la Geltrú",
  "Vilassar de Dalt",
  "Vilassar de Mar",
  "Vilobí d'Onyar",
];
