export const CATEGORIAS_CERTIFICACION = [
  "Microsoft",
  "Cisco Networking Academy",
  "Splunk",
  "Linux Professional Institute",
  "EC-Council",
  "Scrum Manager",
  "Docker",
  "Kubernetes",
  "Oracle",
  "Unity",
  "Python Institute",
  "Project Management Institute (PMI)",
  "English for IT",
  "ITIL",
  "ATC Authorized Training Center",
  "Meta",
  "Critical Career Skills",
] as const;
