export type Programa = {
  slug: string;
  nombre: string;
  tipo: string;
  familia: string;
  duracio: string;
  requisits: string;
  resum: string;
  sortides: string[];
  continuar: string[];
  modulsPrimer: string[];
  modulsSegon: string[];
  escena: string;
  foto?: string;
};

export const PROGRAMES: Programa[] = [
  // ---------- Batxillerat Artístic ----------
  {
    slug: "art-i-disseny",
    nombre: "Batxillerat d'Art i Disseny",
    tipo: "Batxillerat Artístic",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum:
      "Modalitat centrada en el dibuix, el volum i la cultura visual, pensada per a l'alumnat que vol continuar cap a Belles Arts, Disseny, Arquitectura o Conservació i Restauració.",
    sortides: ["Belles Arts", "Disseny gràfic, de moda o d'interiors", "Arquitectura", "Conservació i restauració de béns culturals"],
    continuar: ["Graus universitaris de Belles Arts i Disseny", "Cicles Formatius de Grau Superior d'Arts Plàstiques i Disseny"],
    modulsPrimer: ["Dibuix Artístic I", "Dibuix Tècnic I", "Cultura Audiovisual I", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Dibuix Artístic II", "Volum", "Disseny", "Història de l'Art", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "art",
    foto: "/imes/estudis/art-i-disseny.jpg",
  },
  {
    slug: "arts-esceniques",
    nombre: "Batxillerat d'Arts Escèniques",
    tipo: "Batxillerat Artístic",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum:
      "Formació centrada en la interpretació, la veu i el moviment escènic, amb muntatges i pràctica escènica real com a eix de l'aprenentatge.",
    sortides: ["Interpretació i art dramàtic", "Direcció escènica", "Producció d'espectacles", "Docència de les arts escèniques"],
    continuar: ["Estudis superiors d'Art Dramàtic", "Graus de Comunicació i Humanitats"],
    modulsPrimer: ["Cos i Moviment", "Veu i Dicció", "Anàlisi de l'Obra Dramàtica", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Interpretació", "Cultura Audiovisual II", "Literatura Universal", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "arts",
    foto: "/imes/estudis/arts-esceniques.jpg",
  },
  {
    slug: "audiovisuals",
    nombre: "Batxillerat d'Audiovisuals",
    tipo: "Batxillerat Artístic",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum:
      "Modalitat centrada en el llenguatge cinematogràfic, la gravació i l'edició, amb projectes audiovisuals propis des del primer curs.",
    sortides: ["Direcció i realització audiovisual", "Fotografia", "Edició i postproducció", "Comunicació audiovisual"],
    continuar: ["Grau en Comunicació Audiovisual", "Cinema i mitjans audiovisuals", "CFGS d'Imatge i So"],
    modulsPrimer: ["Cultura Audiovisual I", "Fonaments d'Imatge", "Dibuix Tècnic I", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Cultura Audiovisual II", "Realització Audiovisual", "Disseny", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "audiovisuals",
    foto: "/imes/estudis/audiovisuals.jpg",
  },
  {
    slug: "produccio-musical",
    nombre: "Batxillerat de Producció Musical",
    tipo: "Batxillerat Artístic",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum:
      "Formació en composició, enregistrament i tecnologia musical, amb accés a estudi de gravació i pràctica musical en directe.",
    sortides: ["Producció musical i enregistrament", "Composició", "So en directe i tècnic de so", "Indústria musical"],
    continuar: ["Estudis superiors de Música", "Enginyeria de so", "CFGS de So per a Audiovisuals"],
    modulsPrimer: ["Llenguatge i Pràctica Musical I", "Cultura Audiovisual I", "Anàlisi Musical I", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Llenguatge i Pràctica Musical II", "Història de la Música", "Anàlisi Musical II", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "musica",
    foto: "/imes/estudis/produccio-musical.jpg",
  },
  {
    slug: "humanistic",
    nombre: "Batxillerat Humanístic",
    tipo: "Batxillerat",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum: "Formació general orientada a lletres, filosofia i ciències socials, com a base sòlida per a estudis universitaris humanístics.",
    sortides: ["Filologia i Traducció", "Història", "Dret", "Periodisme i Comunicació"],
    continuar: ["Graus universitaris d'Humanitats i Ciències Socials"],
    modulsPrimer: ["Llatí I", "Grec I", "Història del Món Contemporani", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Llatí II", "Grec II", "Literatura Universal", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "comunitat",
    foto: "/imes/estudis/batxillerat-humanistic.jpg",
  },
  {
    slug: "social",
    nombre: "Batxillerat Social",
    tipo: "Batxillerat",
    familia: "Batxillerats",
    duracio: "2 cursos acadèmics",
    requisits: "Graduat en ESO o equivalent",
    resum: "Formació general orientada a l'àmbit social, educatiu i psicològic, com a base per a Pedagogia, Psicologia o Treball Social.",
    sortides: ["Psicologia", "Pedagogia i Educació Social", "Treball Social", "Sociologia"],
    continuar: ["Graus universitaris de Ciències Socials i Educació"],
    modulsPrimer: ["Economia", "Ciències per al Món Contemporani", "Història del Món Contemporani", "Llengua Catalana i Literatura I", "Llengua Castellana i Literatura I", "Llengua Estrangera I", "Educació Física", "Filosofia"],
    modulsSegon: ["Psicologia", "Geografia", "Literatura Universal", "Llengua Catalana i Literatura II", "Llengua Castellana i Literatura II", "Llengua Estrangera II", "Història"],
    escena: "comunitat",
    foto: "/imes/estudis/batxillerat-social.jpg",
  },
  // ---------- FP Comerç i Màrqueting ----------
  {
    slug: "activitats-comercials",
    nombre: "Activitats Comercials",
    tipo: "CFGM",
    familia: "Comerç i Màrqueting",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Graduat en ESO o prova d'accés",
    resum: "Formació per gestionar i executar activitats de venda, atenció al client i organització d'un punt de venda.",
    sortides: ["Venedor/a tècnic/a", "Representant comercial", "Responsable de punt de venda", "Teleoperador/a comercial"],
    continuar: ["CFGS de Comerç Internacional o Màrqueting i Publicitat", "Batxillerat"],
    modulsPrimer: ["Vendes", "Aplicacions Informàtiques per al Comerç", "Aparadorisme", "Anglès Tècnic", "Formació i Orientació Laboral"],
    modulsSegon: ["Tècniques d'Emmagatzematge", "Gestió d'un Petit Comerç", "Comerç Electrònic", "Empresa i Iniciativa Emprenedora", "Formació en Centres de Treball (FCT)"],
    escena: "comerc",
    foto: "/imes/estudis/activitats-comercials.jpg",
  },
  {
    slug: "publicitat-i-marqueting",
    nombre: "Publicitat i Màrqueting",
    tipo: "CFGS",
    familia: "Comerç i Màrqueting",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per dissenyar i executar accions de màrqueting, publicitat i comunicació comercial, també en l'entorn digital.",
    sortides: ["Tècnic/a de màrqueting", "Gestor/a de xarxes socials", "Assistent de publicitat", "Coordinador/a de campanyes"],
    continuar: ["Grau en Màrqueting o Publicitat i Relacions Públiques"],
    modulsPrimer: ["Investigació Comercial", "Màrqueting Digital", "Polítiques de Màrqueting", "Disseny i Elaboració de Material de Comunicació", "Anglès Tècnic"],
    modulsSegon: ["Gestió de la Publicitat i Esdeveniments de Màrqueting", "Comunicació i Atenció al Client", "Treball de Camp en la Investigació Comercial", "Projecte de Màrqueting", "FCT"],
    escena: "comerc",
    foto: "/imes/estudis/publicitat-marqueting.jpg",
  },
  {
    slug: "comerc-internacional",
    nombre: "Comerç Internacional",
    tipo: "CFGS",
    familia: "Comerç i Màrqueting",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per gestionar operacions de compravenda internacional, logística d'importació-exportació i finançament exterior.",
    sortides: ["Tècnic/a de comerç exterior", "Gestor/a d'importació-exportació", "Agent de duanes", "Comercial internacional"],
    continuar: ["Grau en Comerç Internacional o Administració i Direcció d'Empreses"],
    modulsPrimer: ["Comerç Internacional", "Gestió Econòmica i Financera de l'Empresa", "Anglès Tècnic", "Màrqueting Internacional", "Logística d'Emmagatzematge"],
    modulsSegon: ["Finançament Internacional", "Mitjans de Pagament Internacionals", "Transport Internacional de Mercaderies", "Projecte de Comerç Internacional", "FCT"],
    escena: "comerc",
    foto: "/imes/estudis/comerc-internacional.jpg",
  },
  // ---------- FP Informàtica i Comunicació ----------
  {
    slug: "sistemes-microinformatics-i-xarxes",
    nombre: "Sistemes Microinformàtics i Xarxes (SIMIX)",
    tipo: "CFGM",
    familia: "Informàtica i Comunicació",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Graduat en ESO o prova d'accés",
    resum: "Formació per instal·lar, configurar i mantenir sistemes microinformàtics, aïllats o en xarxa, i donar suport a l'usuari.",
    sortides: ["Tècnic/a de suport informàtic", "Instal·lador/a de xarxes", "Reparador/a d'equips microinformàtics"],
    continuar: ["CFGS d'ASIX, DAM o Ciberseguretat", "Batxillerat"],
    modulsPrimer: ["Muntatge i Manteniment d'Equips", "Sistemes Operatius Monolloc", "Aplicacions Ofimàtiques", "Xarxes Locals", "Formació i Orientació Laboral"],
    modulsSegon: ["Sistemes Operatius en Xarxa", "Serveis en Xarxa", "Aplicacions Web", "Seguretat Informàtica", "Empresa i Iniciativa Emprenedora", "FCT"],
    escena: "informatica",
    foto: "/imes/estudis/simix.jpg",
  },
  {
    slug: "administracio-de-sistemes-informatics-en-xarxa",
    nombre: "Administració de Sistemes Informàtics en Xarxa (ASIX)",
    tipo: "CFGS",
    familia: "Informàtica i Comunicació",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació avançada per configurar, administrar i mantenir sistemes informàtics i xarxes, garantint-ne la seguretat i disponibilitat.",
    sortides: ["Administrador/a de sistemes", "Tècnic/a de xarxes", "Responsable d'infraestructura IT"],
    continuar: ["Grau universitari d'Informàtica", "Cursos d'especialització en ciberseguretat"],
    modulsPrimer: ["Implantació de Sistemes Operatius", "Planificació i Administració de Xarxes", "Gestió de Bases de Dades", "Llenguatges de Marques", "Anglès Tècnic"],
    modulsSegon: ["Administració de Sistemes Gestors de Bases de Dades", "Serveis de Xarxa i Internet", "Implantació d'Aplicacions Web", "Seguretat i Alta Disponibilitat", "Projecte d'ASIX", "FCT"],
    escena: "informatica",
    foto: "/imes/estudis/asix.jpg",
  },
  {
    slug: "desenvolupament-dapps-multiplataforma",
    nombre: "Desenvolupament d'Apps Multiplataforma (DAM)",
    tipo: "CFGS",
    familia: "Informàtica i Comunicació",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació en programació i disseny d'aplicacions per a diferents plataformes: escriptori, web i mòbil.",
    sortides: ["Programador/a d'aplicacions", "Desenvolupador/a mòbil", "Analista programador/a"],
    continuar: ["Grau universitari d'Enginyeria Informàtica"],
    modulsPrimer: ["Programació", "Bases de Dades", "Llenguatges de Marques", "Sistemes Informàtics", "Anglès Tècnic"],
    modulsSegon: ["Desenvolupament d'Interfícies", "Programació Multimèdia i Dispositius Mòbils", "Accés a Dades", "Sistemes de Gestió Empresarial", "Projecte de DAM", "FCT"],
    escena: "informatica",
    foto: "/imes/estudis/dam.jpg",
  },
  // ---------- FP Administració i Gestió d'Empreses ----------
  {
    slug: "administracio-i-finances",
    nombre: "Administració i Finances",
    tipo: "CFGS",
    familia: "Administració i Gestió d'Empreses",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per organitzar i executar la gestió administrativa, comptable, fiscal i laboral d'una empresa.",
    sortides: ["Administratiu/va comptable", "Gestor/a de nòmines", "Tècnic/a de gestió financera", "Assessor/a fiscal"],
    continuar: ["Grau en Administració i Direcció d'Empreses, Economia o Dret"],
    modulsPrimer: ["Comptabilitat i Fiscalitat", "Gestió de la Documentació Jurídica i Empresarial", "Procés Integral de l'Activitat Comercial", "Anglès Tècnic", "Ofimàtica i Procés de la Informació"],
    modulsSegon: ["Gestió Financera", "Comptabilitat i Fiscalitat", "Gestió Logística i Comercial", "Simulació Empresarial", "Projecte d'Administració i Finances", "FCT"],
    escena: "comerc",
  },
  // ---------- FP Sanitat ----------
  {
    slug: "cures-auxiliars-dinfermeria",
    nombre: "Cures Auxiliars d'Infermeria",
    tipo: "CFGM",
    familia: "Sanitat",
    duracio: "1.400 hores · 1 curs acadèmic",
    requisits: "Graduat en ESO o prova d'accés",
    resum: "Formació intensiva d'un any per treballar com a auxiliar d'infermeria, oferint cures sanitàries bàsiques en centres sanitaris i hospitalaris.",
    sortides: ["Auxiliar d'infermeria en hospital", "Auxiliar d'atenció primària o domiciliària", "Auxiliar de salut mental"],
    continuar: ["CFGS de Dietètica o Laboratori Clínic i Biomèdic"],
    modulsPrimer: ["Tècniques Bàsiques d'Infermeria", "Higiene del Medi Hospitalari i Neteja de Material", "Promoció de la Salut i Suport Psicològic al Pacient", "Primers Auxilis", "Formació i Orientació Laboral"],
    modulsSegon: ["Relacions en l'Equip de Treball", "Operacions Administratives i Documentació Sanitària", "Fonaments i Tècniques d'Infermeria en Salut Mental", "Formació en Centres de Treball (FCT)"],
    escena: "sanitat",
  },
  {
    slug: "dietetica",
    nombre: "Dietètica",
    tipo: "CFGS",
    familia: "Sanitat",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per elaborar plans d'alimentació i educar en hàbits nutricionals saludables, en àmbits clínics i comunitaris.",
    sortides: ["Dietista-nutricionista tècnic/a", "Educador/a en alimentació saludable", "Tècnic/a de restauració col·lectiva"],
    continuar: ["Grau en Nutrició Humana i Dietètica"],
    modulsPrimer: ["Alimentació Equilibrada", "Fisiopatologia Aplicada a la Dietètica", "Control Alimentari", "Organització i Gestió de l'Àrea de Treball Assignada a l'Àmbit de la Seva Competència", "Anglès Tècnic"],
    modulsSegon: ["Dietoteràpia", "Microbiologia i Higiene Alimentària", "Educació Sanitària i Promoció de la Salut", "Relacions en l'Equip de Treball", "Projecte de Dietètica", "FCT"],
    escena: "sanitat",
  },
  // ---------- FP Serveis Socioculturals i a la Comunitat ----------
  {
    slug: "educacio-infantil-gs",
    nombre: "Educació Infantil",
    tipo: "CFGS",
    familia: "Serveis Socioculturals i a la Comunitat",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per dissenyar, implementar i avaluar projectes educatius amb infants de 0 a 6 anys, en l'àmbit formal i no formal.",
    sortides: ["Educador/a infantil", "Auxiliar en escoles bressol", "Monitor/a de lleure infantil"],
    continuar: ["Grau en Educació Infantil o Primària", "Grau en Pedagogia"],
    modulsPrimer: ["Didàctica de l'Educació Infantil", "Autonomia Personal i Salut Infantil", "El Joc Infantil i la seva Metodologia", "Expressió i Comunicació", "Anglès Tècnic"],
    modulsSegon: ["Desenvolupament Cognitiu i Motriu", "Desenvolupament Socioafectiu", "Habilitats Socials", "Intervenció amb Famílies i Atenció a Menors en Risc Social", "Projecte d'Educació Infantil", "FCT"],
    escena: "comunitat",
  },
  {
    slug: "integracio-social",
    nombre: "Integració Social",
    tipo: "CFGS",
    familia: "Serveis Socioculturals i a la Comunitat",
    duracio: "2.000 hores · 2 cursos acadèmics",
    requisits: "Batxillerat o CFGM amb prova d'accés",
    resum: "Formació per acompanyar processos d'inclusió social de persones i col·lectius en risc d'exclusió, dissenyant i executant programes d'intervenció.",
    sortides: ["Tècnic/a d'integració social", "Educador/a social", "Mediador/a comunitari"],
    continuar: ["Grau en Educació Social o Treball Social"],
    modulsPrimer: ["Context de la Intervenció Social", "Promoció de l'Autonomia Personal", "Inserció Sociolaboral", "Habilitats Socials", "Anglès Tècnic"],
    modulsSegon: ["Atenció a les Unitats de Convivència", "Mediació Comunitària", "Sistemes Augmentatius i Alternatius de Comunicació", "Suport a la Intervenció Educativa", "Projecte d'Integració Social", "FCT"],
    escena: "comunitat",
  },
];

export function getPrograma(slug: string) {
  return PROGRAMES.find((p) => p.slug === slug);
}
